### ISSUE TITLE
gemini api error

### ISSUE THREAD

**Issue by codeblech** [codeblech/foodlabel#2]
```
Traceback (most recent call last):
  File "/home/malik/Documents/Programming/minor 😛/foodlabel/blinkit.py", line 118, in <module>
    response = model.generate_content(prompt + image_list)
  File "/home/malik/.cache/pypoetry/virtualenvs/foodlabel-eue2fuw4-py3.10/lib/python3.10/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
  File "/home/malik/.cache/pypoetry/virtualenvs/foodlabel-eue2fuw4-py3.10/lib/python3.10/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 830, in generate_content
    response = rpc(
  File "/home/malik/.cache/pypoetry/virtualenvs/foodlabel-eue2fuw4-py3.10/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/malik/.cache/pypoetry/virtualenvs/foodlabel-eue2fuw4-py3.10/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/home/malik/.cache/pypoetry/virtualenvs/foodlabel-eue2fuw4-py3.10/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/malik/.cache/pypoetry/virtualenvs/foodlabel-eue2fuw4-py3.10/lib/python3.10/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/malik/.cache/pypoetry/virtualenvs/foodlabel-eue2fuw4-py3.10/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/home/malik/.cache/pypoetry/virtualenvs/foodlabel-eue2fuw4-py3.10/lib/python3.10/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/malik/.cache/pypoetry/virtualenvs/foodlabel-eue2fuw4-py3.10/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InternalServerError: 500 An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting
```

**Comment by codeblech** [comment]
simply retrying results in no error. is it due to ratelimiting?
